# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8642ec7c4416442ac31a78f4fd31408d71974dbea64ce6bf151123324e363cdfdde2b5f8913625bcebb70e826473030fe0b9b2e748179870d19a486b403bcbbb

test:
  secret_key_base: 8b778b3cd062364c20b82f0b373ef73e0231db80a1a0172ee3129cbf5795ed1629a49e0c15223481e961e34340c5ced2440ffbfb5f4d02022d67a3b3a030131e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
